=== srinidhib07/EP_PRACTICAL/Lab1/Task2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Student_info (student+)>
<!ELEMENT student (regno, name, avg, dob, time, mobile, distinction)>
<!ELEMENT regno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT avg (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT distinction (#PCDATA)>

=== srinidhib07/EP_PRACTICAL/Lab1/Task2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Student_info SYSTEM "Task2.dtd">
<Student_info>
	<student>
		<regno>19001</regno>
		<name>Sreya</name>
		<avg>95</avg>
		<dob>12-12-2001</dob>
		<time>15.00</time>
		<mobile>9909284839</mobile>
		<distinction>YES</distinction>
	</student>

	<student>
		<regno>19002</regno>
		<name>Ramya</name>
		<avg>91</avg>
		<dob>01-10-2002</dob>
		<time>10.00</time>
		<mobile>9943988934</mobile>
		<distinction>YES</distinction>

	</student>

	<student>
		<regno>19003</regno>
		<name>Lasya</name>
		<avg>88</avg>
		<dob>09-08-2002</dob>
		<time>11.45</time>
		<mobile>98902229384</mobile>
		<distinction>NO</distinction>

	</student>

	<student>
		<regno>19008</regno>
		<name>Nithya</name>
		<avg>98</avg>
		<dob>07-04-2002</dob>
		<time>10.00</time>
		<mobile>9943980234</mobile>
		<distinction>YES</distinction>

	</student>

	<student>
		<regno>19009</regno>
		<name>Sasha</name>
		<avg>93</avg>
		<dob>01-10-2002</dob>
		<time>2.30</time>
		<mobile>9943988934</mobile>
		<distinction>YES</distinction>

	</student>


</Student_info>
